**Lab 2**
Part 1


**First We will summarize each of the following Libaries.**
Libary one:
1) ***NLTK:***
This Platform Main goal is to make a bridge between Python programs and human languages data such as documents. The platform works with over 50 corporas(large strucuted sets of texts which are used for NLP works) and lexical resources.
It's main abiliites that are relevent for our Dicts : Tokenization,Lemmatization,Stemming,Named Entity Recognition (NER),Synonyms(using wordnet) and WSD.
2) ***TextBlob***
This Libary is for processing textual data,The idea is to provide a simple API for working on NLPs tasks.
It's main abiliites that are relevent for our Dicts :Tokenizations,lemmatizations,Spelling corrections.
2) ***spaCy***
Open-source libary,designed for producion use and helps to build apps "understand" large volumes of text.
It's main abiliites that are relevent for our Dicts:Tokenization,Lemmatization,
WSD(limited),NER.

In [ ]:
#Lets Install all the libaries first.
# %pip  install nltk
# %pip install numpy
# %pip install TextBlob
# %pip install spaCy
# %pip install pandas
%pip install scikit-learn


In [15]:
#Testing that the libaries are installed
try:
    import nltk
    print(f"NLTK is installed. Version: {nltk.__version__}")
except ImportError:
    print("NLTK is not installed.")

try:
    from textblob import TextBlob
    print("TextBlob is installed.")
except ImportError:
    print("TextBlob is not installed.")

try:
    import spacy
    print(f"SpaCy is installed. Version: {spacy.__version__}")
except ImportError:
    print("SpaCy is not installed.")



NLTK is installed. Version: 3.9.1
TextBlob is installed.
SpaCy is installed. Version: 3.8.3


In [ ]:
#Now we will test the libaries and their abillites on arteficual text.(60 words)
Art_text = "Jhon visited the bank to depsoit $500. He noticed the river bnak nearby was bustling with activty. AI is tranforming industres, especially helthcare and finance. NLP tols help anaylze txt. NASA recently annonced a mission to Mars, sparking global excitment. The CEO of Gogle praised inovation during his keynott speach."
# import nltk
# nltk.download('punkt_tab')
# nltk.download('wordnet')

In [7]:
#Lets start With NLTK:
#Abillites that it can run:Tokenization,Lemmatization,Stemming,Named Entity 
# Recognition (NER),Synonyms(using wordnet) and WSD.

import nltk as nd
import pandas as pd
#Tokenize

Art_text_tokenize =  nd.word_tokenize(Art_text)
print("The Text in tokenize form",Art_text_tokenize)

#Lemmatization- will print only the ones that it changed.
wnl = nd.WordNetLemmatizer()
word_after={}
word_before={}
words_lemmatized = {}

for i,word in enumerate(Art_text_tokenize):
    word_before[i] = Art_text_tokenize[i]
    word_after[i] = wnl.lemmatize(Art_text_tokenize[i])
    if(word_after != word_before):
        words_lemmatized[i] = word_after

print("The lemmatized words",words_lemmatized)



The Text in tokenize form ['Jhon', 'visited', 'the', 'bank', 'to', 'depsoit', '$', '500', '.', 'He', 'noticed', 'the', 'river', 'bnak', 'nearby', 'was', 'bustling', 'with', 'activty', '.', 'AI', 'is', 'tranforming', 'industres', ',', 'especially', 'helthcare', 'and', 'finance', '.', 'NLP', 'tols', 'help', 'anaylze', 'txt', '.', 'NASA', 'recently', 'annonced', 'a', 'mission', 'to', 'Mars', ',', 'sparking', 'global', 'excitment', '.', 'The', 'CEO', 'of', 'Gogle', 'praised', 'inovation', 'during', 'his', 'keynott', 'speach', '.']
The lemmatized words {15: {0: 'Jhon', 1: 'visited', 2: 'the', 3: 'bank', 4: 'to', 5: 'depsoit', 6: '$', 7: '500', 8: '.', 9: 'He', 10: 'noticed', 11: 'the', 12: 'river', 13: 'bnak', 14: 'nearby', 15: 'wa', 16: 'bustling', 17: 'with', 18: 'activty', 19: '.', 20: 'AI', 21: 'is', 22: 'tranforming', 23: 'industres', 24: ',', 25: 'especially', 26: 'helthcare', 27: 'and', 28: 'finance', 29: '.', 30: 'NLP', 31: 'tols', 32: 'help', 33: 'anaylze', 34: 'txt', 35: '.', 36: 

In [21]:
#Stemming
#we will take again the same Art_text_tokenize

from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")
word_stemed = {}
word_after={}
word_before={}
word_before_stemed = {}
for i,word in enumerate(Art_text_tokenize):
    word_before[i] = Art_text_tokenize[i]
    word_after[i] = stemmer.stem(Art_text_tokenize[i])
    if word_after != word_before:
        word_before_stemed[i] = word_before[i]
        word_stemed[i] = word_after
print(f"Words that have been stemmed",word_stemed)
print(f"Words that have before being stemmed",word_before_stemed)

Words that have been stemmed {0: {0: 'jhon', 1: 'visit', 2: 'the', 3: 'bank', 4: 'to', 5: 'depsoit', 6: '$', 7: '500', 8: '.', 9: 'he', 10: 'notic', 11: 'the', 12: 'river', 13: 'bnak', 14: 'nearbi', 15: 'was', 16: 'bustl', 17: 'with', 18: 'activti', 19: '.', 20: 'ai', 21: 'is', 22: 'tranform', 23: 'industr', 24: ',', 25: 'especi', 26: 'helthcar', 27: 'and', 28: 'financ', 29: '.', 30: 'nlp', 31: 'tol', 32: 'help', 33: 'anaylz', 34: 'txt', 35: '.', 36: 'nasa', 37: 'recent', 38: 'annonc', 39: 'a', 40: 'mission', 41: 'to', 42: 'mar', 43: ',', 44: 'spark', 45: 'global', 46: 'excit', 47: '.', 48: 'the', 49: 'ceo', 50: 'of', 51: 'gogl', 52: 'prais', 53: 'inov', 54: 'dure', 55: 'his', 56: 'keynott', 57: 'speach', 58: '.'}, 1: {0: 'jhon', 1: 'visit', 2: 'the', 3: 'bank', 4: 'to', 5: 'depsoit', 6: '$', 7: '500', 8: '.', 9: 'he', 10: 'notic', 11: 'the', 12: 'river', 13: 'bnak', 14: 'nearbi', 15: 'was', 16: 'bustl', 17: 'with', 18: 'activti', 19: '.', 20: 'ai', 21: 'is', 22: 'tranform', 23: 'indus

In [14]:
#Installations for NER
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('maxent_ne_chunker_tab')
nltk.download('words')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\filex\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     C:\Users\filex\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping chunkers\maxent_ne_chunker_tab.zip.
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\filex\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.


True

In [49]:
#NLTK Named Entity 
# Recognition (NER)
#We will use POS_Tags So the NER modal could work better.
from nltk import pos_tag, ne_chunk

pos_tags = pos_tag(Art_text_tokenize)
ner_tree = ne_chunk(pos_tags)
entites = []

for text in ner_tree:
    if hasattr(text,'label'):
        entity_name = " ".join([leaf[0] for leaf in text])
        entity_type = text.label()
        entites.append((entity_name, entity_type))

print("Entites",entites) 

#Synonyms
from nltk.corpus import wordnet
words_with_synonyms = []

for word in Art_text_tokenize:
    word = word.lower()
    synsets = wordnet.synsets(word)
    if wordnet.synsets(word):
        if(word != synsets):
            words_with_synonyms.append((word, synsets[0].name()))
words_with_synonyms = list(set(words_with_synonyms))
print("Words with at least one synonym and their synsets:")
formatted_output = ', '.join([f"{word}: {synset}" for word, synset in words_with_synonyms])
print(formatted_output)

#WSD
from nltk.wsd import lesk
#we will try to use sentances to get context.
sentences = nltk.sent_tokenize(Art_text)
tokenized_sentences = [nltk.word_tokenize(sentence) for sentence in sentences]
word_senses = []

for sentence in tokenized_sentences:
    for word in sentence:
        sense = lesk(sentence, word)  
        if sense: 
            word_senses.append((word, sense.name(), sense.definition()))

# Display the results
print("")
print("Words with their disambiguated senses and definitions:")
for word, synset_name, definition in word_senses:
    print(f"{word}: {synset_name} - {definition}")

Entites [('Jhon', 'PERSON'), ('NLP', 'ORGANIZATION'), ('NASA', 'ORGANIZATION'), ('Mars', 'PERSON'), ('CEO of Gogle', 'ORGANIZATION')]
Words with at least one synonym and their synsets:
ceo: chief_executive_officer.n.01, he: helium.n.01, ai: army_intelligence.n.01, visited: visit.v.01, praised: praise.v.01, finance: finance.n.01, mars: mars.n.01, nearby: nearby.s.01, noticed: detect.v.01, is: be.v.01, especially: particularly.r.01, mission: mission.n.01, was: washington.n.02, bank: bank.n.01, nasa: national_aeronautics_and_space_administration.n.01, sparking: trip.v.04, river: river.n.01, 500: five_hundred.n.01, help: aid.n.02, nlp: natural_language_processing.n.01, bustling: bustle.v.01, recently: recently.r.01, a: angstrom.n.01, global: global.s.01

Words with their disambiguated senses and definitions:
visited: visit.v.04 - come to see in an official or professional capacity
bank: bank.v.07 - cover with ashes so to control the rate of burning
500: five_hundred.s.01 - denoting a quant

In [59]:
#Lets move to TextBlob
#Tokenizations,lemmatizations,Spelling corrections.
from textblob import TextBlob 
#Tokenization
blob_obj = TextBlob(Art_text)
blob_tokenize = blob_obj.words
print("Tokenization :",blob_tokenize)

#Lemmatizations
blob_lem=[word.lemmatize() for word in blob_tokenize]
print(blob_lem)

#Spelling Corrections
for i,word in enumerate(blob_tokenize):
    word_before = blob_tokenize[i]
    word_after =blob_tokenize[i].correct()
    if word_before != word_after:
        print(f"word before :",{word_before},"after:",{word_after})

Tokenization : ['Jhon', 'visited', 'the', 'bank', 'to', 'depsoit', '500', 'He', 'noticed', 'the', 'river', 'bnak', 'nearby', 'was', 'bustling', 'with', 'activty', 'AI', 'is', 'tranforming', 'industres', 'especially', 'helthcare', 'and', 'finance', 'NLP', 'tols', 'help', 'anaylze', 'txt', 'NASA', 'recently', 'annonced', 'a', 'mission', 'to', 'Mars', 'sparking', 'global', 'excitment', 'The', 'CEO', 'of', 'Gogle', 'praised', 'inovation', 'during', 'his', 'keynott', 'speach']
['Jhon', 'visited', 'the', 'bank', 'to', 'depsoit', '500', 'He', 'noticed', 'the', 'river', 'bnak', 'nearby', 'wa', 'bustling', 'with', 'activty', 'AI', 'is', 'tranforming', 'industres', 'especially', 'helthcare', 'and', 'finance', 'NLP', 'tols', 'help', 'anaylze', 'txt', 'NASA', 'recently', 'annonced', 'a', 'mission', 'to', 'Mars', 'sparking', 'global', 'excitment', 'The', 'CEO', 'of', 'Gogle', 'praised', 'inovation', 'during', 'his', 'keynott', 'speach']
word before : {'Jhon'} after: {'Hon'}
word before : {'depsoit'

In [9]:
#SPACY
# Tokenization,Lemmatization, WSD(limited),NER.
from spacy.tokenizer import Tokenizer
from spacy.lang.en import English
import spacy
nlp = English()#english pipline

tokenizer = nlp.tokenizer
tokens = tokenizer(Art_text)
Art_token = [token.text for token in tokens]
print("Art_token",Art_token)

#Lemmatization
#spacy.cli.download("en_core_web_sm")

nlp = spacy.load("en_core_web_sm")

doc = nlp(Art_text) #we need a raw version.
print("Lemmatization",[token.lemma_ for token in doc])

#NER
for ent in doc.ents:
    print(f"Entity: {ent.text}, Label: {ent.label_}")

Art_token ['Jhon', 'visited', 'the', 'bank', 'to', 'depsoit', '$', '500', '.', 'He', 'noticed', 'the', 'river', 'bnak', 'nearby', 'was', 'bustling', 'with', 'activty', '.', 'AI', 'is', 'tranforming', 'industres', ',', 'especially', 'helthcare', 'and', 'finance', '.', 'NLP', 'tols', 'help', 'anaylze', 'txt', '.', 'NASA', 'recently', 'annonced', 'a', 'mission', 'to', 'Mars', ',', 'sparking', 'global', 'excitment', '.', 'The', 'CEO', 'of', 'Gogle', 'praised', 'inovation', 'during', 'his', 'keynott', 'speach', '.']
Lemmatization ['Jhon', 'visit', 'the', 'bank', 'to', 'depsoit', '$', '500', '.', 'he', 'notice', 'the', 'river', 'bnak', 'nearby', 'be', 'bustle', 'with', 'activty', '.', 'AI', 'be', 'tranforme', 'industre', ',', 'especially', 'helthcare', 'and', 'finance', '.', 'NLP', 'tol', 'help', 'anaylze', 'txt', '.', 'NASA', 'recently', 'annonce', 'a', 'mission', 'to', 'Mars', ',', 'spark', 'global', 'excitment', '.', 'the', 'ceo', 'of', 'Gogle', 'praise', 'inovation', 'during', 'his', 'ke

**part 4**
Working on our choosen docs for lab 1.

In [17]:
import nltk
nltk.download('punkt_tab') #punctuations
nltk.download('stopwords')#Stopwords.
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\filex\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\filex\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\filex\AppData\Roaming\nltk_data...


True

In [14]:

import pandas as pd
import re
cats = ['comp.windows.x', 'sci.space'] #getting two options
from sklearn.datasets import fetch_20newsgroups
from nltk.tokenize import sent_tokenize, word_tokenize #Libray to tokenize the words.
from nltk.corpus import stopwords
import string  
from sklearn.feature_extraction.text import CountVectorizer  #Libary from Counters.

newsgroups = fetch_20newsgroups(subset='all', categories=cats)


#lets do some preprocessing
#First lets combine them into one big category.
category_texts_unified = [
    {"text": doc, "category": newsgroups.target_names[target]}
    for doc, target in zip(newsgroups.data, newsgroups.target)
    if target in [newsgroups.target_names.index(cat) for cat in cats]
]
stops = set(stopwords.words('english')) # stopword from english.

#Removing Lowercases,non-alphabetical characters
#Tokenizeing ,removing stopwords and punctuation
Clean_text = []
for doc in category_texts_unified:
    text = re.sub(r'[^a-zA-Z\s]', '', doc["text"].lower())
    words = word_tokenize(text)
    filtered_words = [w for w in words if w not in stops and w not in string.punctuation]
    # Save cleaned text with category
    Clean_text.append({"text": ' '.join(filtered_words), "category": doc["category"]})



#Let's look for mispalling.
mispalled_words = []
for entry in Clean_text:
    # Tokenize the cleaned text
    words = word_tokenize(entry["text"])
    for word in words:
        blob = TextBlob(word)
        corrected_word = str(blob.correct())
        if corrected_word != word:
            mispalled_words.append((word, corrected_word))

# import pickle

# # Save preprocessed data to a Pickle file
# with open("preprocessed_data.pkl", "wb") as f:
#     pickle.dump(Clean_text, f)

# print("Data saved to preprocessed_data.pkl")



Data saved to preprocessed_data.pkl


Now after preprocssing, We will start doing the abilities we mentioned in the begining.
We can conclude that fixing mispalling takes the most time and effort, therefore as part of our attempts to find the best algorthem for both accurcy and time efficency.
We will judge the outputs on how many ACRONYM,SYNONYMS,WSD,NER;we got on each test.
#For the first test, We will do :
1)lemmatization-nltk 
2)stemming -nltk
3)Synonyms -nltk using wordnet
4)WSD-nltk
5)NER-nltk

In [21]:
import pickle
import time
import nltk as nd
from nltk import pos_tag, ne_chunk

with open('preprocessed_data.pkl', 'rb') as f:
    data = pickle.load(f)
 
start_time_overall = time.time() #Starting the timer.
#Tokenization
start_time_task = time.time()
data_tokenized = []
for entry in data:
    tokenized_data = nd.word_tokenize(entry["text"])
    data_tokenized.extend(tokenized_data)  # Flatten tokens into a single list

end_time_task = time.time()
print("Tokenization time:",end_time_task-start_time_task)

#lemmatization
start_time_task = time.time()
wnl = nd.WordNetLemmatizer()

words_lemmatized = {}

for i,word in enumerate(data_tokenized):
    word_afte = wnl.lemmatize(word)
    if(word_afte != word):
        words_lemmatized[i] = (word,word_afte)
end_time_task = time.time()
print("lemmatization time:",end_time_task-start_time_task)

#stemming
start_time_task = time.time()
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")
word_stemed = {}

for i,word in enumerate(data_tokenized):
    stemed_word = stemmer.stem(word)
    if stemed_word != word:
        word_stemed[i] = (word,stemed_word)

end_time_task = time.time()
print("Stemming time:",end_time_task-start_time_task)


#Synonyms-we will count the amout of words that have at least two synonyms
start_time_task = time.time()

from nltk.corpus import wordnet
words_with_synonyms = {}

for word in data_tokenized:
    synsets = wordnet.synsets(word)
    if len(synsets)>=2: #checks if there is at least two synonmys per word.
        synonyms = {lemma.name() for syn in synsets for lemma in syn.lemmas()}
        if len(synonyms) >= 2:  # Check if there are at least two distinct synonyms
            words_with_synonyms[word] = list(synonyms)

end_time_task = time.time()
print("Synonyms time:",end_time_task-start_time_task)


#WSD
from nltk.wsd import lesk

#we will try to use sentances to get context.
start_time_task = time.time()

text_string = " ".join(data_tokenized)
sentences = nd.sent_tokenize(text_string)
tokenized_sentences = [nd.word_tokenize(sentence) for sentence in sentences]

word_senses = []

for sentence in tokenized_sentences:
    for word in sentence:
        sense = lesk(sentence, word)  
        if sense: 
            word_senses.append((word, sense.name(), sense.definition()))
end_time_task = time.time()
print("WSD time:",end_time_task-start_time_task)



#NER
start_time_task = time.time()
pos_tags = pos_tag(data_tokenized)
ner_tree = ne_chunk(pos_tags)
entites = []

for text in ner_tree:
    if hasattr(text,'label'):
        entity_name = " ".join([leaf[0] for leaf in text])
        entity_type = text.label()
        entites.append((entity_name, entity_type))

end_time_task = time.time()
print("NER time:",end_time_task-start_time_task)


end_time = time.time()
exc_time = end_time-start_time_overall


# Display the results
print("The Results are in!")
print(f'The amount of lemmatized words: {len(words_lemmatized)}')
print(f'The amount of stemmed words: {len(word_stemed)}')
print(f'The amount of words with at least two synonyms: {len(words_with_synonyms)}')
print(f'The amount of NER entities found: {len(entites)}')
print(f'The amount of words with sense found (WSD): {len(word_senses)}')
print("Overall time it took:",exc_time)

Tokenization time: 1.8750958442687988
lemmatization time: 1.8051435947418213
Stemming time: 4.695420265197754
Synonyms time: 7.5493669509887695
WSD time: 9809.51560473442
NER time: 91.48276424407959
The Results are in!
The amount of lemmatized words: 33513
The amount of stemmed words: 134885
The amount of words with at least two synonyms: 10405
The amount of NER entities found: 3
The amount of words with sense found (WSD): 257634
Overall time it took: 9916.932371377945


In [1]:
#lets try diffrenet sequence of abiliities.
#1)lemmatization-nltk 
#2)Synonyms -nltk using wordnet
#3)stemming -nltk
#4)NER-nltk
#5)WSD-nltk

import pickle
import time
import nltk as nd
from nltk import pos_tag, ne_chunk

with open('preprocessed_data.pkl', 'rb') as f:
    data = pickle.load(f)

start_time_overall = time.time() #Starting the timer.
#Tokenization
start_time_task = time.time()
data_tokenized = []
for entry in data:
    tokenized_data = nd.word_tokenize(entry["text"])
    data_tokenized.extend(tokenized_data)  # Flatten tokens into a single list

end_time_task = time.time()
print("Tokenization time:",end_time_task-start_time_task)

#lemmatization
start_time_task = time.time()
wnl = nd.WordNetLemmatizer()

words_lemmatized = {}

for i,word in enumerate(data_tokenized):
    word_afte = wnl.lemmatize(word)
    if(word_afte != word):
        words_lemmatized[i] = (word,word_afte)
end_time_task = time.time()
print("lemmatization time:",end_time_task-start_time_task)

#Synonyms-we will count the amout of words that have at least two synonyms
start_time_task = time.time()

from nltk.corpus import wordnet
words_with_synonyms = {}

for word in data_tokenized:
    synsets = wordnet.synsets(word)
    if len(synsets)>=2: #checks if there is at least two synonmys per word.
        synonyms = {lemma.name() for syn in synsets for lemma in syn.lemmas()}
        if len(synonyms) >= 2:  # Check if there are at least two distinct synonyms
            words_with_synonyms[word] = list(synonyms)

end_time_task = time.time()
print("Synonyms time:",end_time_task-start_time_task)

#stemming
start_time_task = time.time()
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")
word_stemed = {}

for i,word in enumerate(data_tokenized):
    stemed_word = stemmer.stem(word)
    if stemed_word != word:
        word_stemed[i] = (word,stemed_word)

end_time_task = time.time()
print("Stemming time:",end_time_task-start_time_task)


#NER
start_time_task = time.time()
pos_tags = pos_tag(data_tokenized)
ner_tree = ne_chunk(pos_tags)
entites = []

for text in ner_tree:
    if hasattr(text,'label'):
        entity_name = " ".join([leaf[0] for leaf in text])
        entity_type = text.label()
        entites.append((entity_name, entity_type))

end_time_task = time.time()
print("NER time:",end_time_task-start_time_task)

#WSD
from nltk.wsd import lesk

#we will try to use sentances to get context.
start_time_task = time.time()

text_string = " ".join(data_tokenized)
sentences = nd.sent_tokenize(text_string)
tokenized_sentences = [nd.word_tokenize(sentence) for sentence in sentences]

word_senses = []

for sentence in tokenized_sentences:
    for word in sentence:
        sense = lesk(sentence, word)  
        if sense: 
            word_senses.append((word, sense.name(), sense.definition()))
end_time_task = time.time()
print("WSD time:",end_time_task-start_time_task)

end_time = time.time()
exc_time = end_time-start_time_overall


# Display the results
print("The Results are in!")
print(f'The amount of lemmatized words: {len(words_lemmatized)}')
print(f'The amount of stemmed words: {len(word_stemed)}')
print(f'The amount of words with at least two synonyms: {len(words_with_synonyms)}')
print(f'The amount of NER entities found: {len(entites)}')
print(f'The amount of words with sense found (WSD): {len(word_senses)}')
print("Overall time it took:",exc_time)


Tokenization time: 1.815438985824585
lemmatization time: 5.336212396621704
Synonyms time: 10.8156259059906
Stemming time: 5.025677919387817
NER time: 94.18226456642151
WSD time: 8215.4396276474
The Results are in!
The amount of lemmatized words: 33513
The amount of stemmed words: 134885
The amount of words with at least two synonyms: 10405
The amount of NER entities found: 3
The amount of words with sense found (WSD): 257634
Overall time it took: 8332.61590385437


Last Test 
#1)WSD-nltk
#2)NER-nltk
#3)lemmatization-nltk 
#4)Synonyms -nltk using wordnet
#5)stemming -nltk



In [2]:
import pickle
import time
import nltk as nd
from nltk import pos_tag, ne_chunk

with open('preprocessed_data.pkl', 'rb') as f:
    data = pickle.load(f)

start_time_overall = time.time() #Starting the timer.
#Tokenization
start_time_task = time.time()
data_tokenized = []
for entry in data:
    tokenized_data = nd.word_tokenize(entry["text"])
    data_tokenized.extend(tokenized_data)  # Flatten tokens into a single list

end_time_task = time.time()
print("Tokenization time:",end_time_task-start_time_task)

#WSD
from nltk.wsd import lesk

#we will try to use sentances to get context.
start_time_task = time.time()

text_string = " ".join(data_tokenized)
sentences = nd.sent_tokenize(text_string)
tokenized_sentences = [nd.word_tokenize(sentence) for sentence in sentences]

word_senses = []

for sentence in tokenized_sentences:
    for word in sentence:
        sense = lesk(sentence, word)  
        if sense: 
            word_senses.append((word, sense.name(), sense.definition()))
end_time_task = time.time()
print("WSD time:",end_time_task-start_time_task)

end_time = time.time()
exc_time = end_time-start_time_overall

#NER
start_time_task = time.time()
pos_tags = pos_tag(data_tokenized)
ner_tree = ne_chunk(pos_tags)
entites = []

for text in ner_tree:
    if hasattr(text,'label'):
        entity_name = " ".join([leaf[0] for leaf in text])
        entity_type = text.label()
        entites.append((entity_name, entity_type))

end_time_task = time.time()
print("NER time:",end_time_task-start_time_task)

#lemmatization
start_time_task = time.time()
wnl = nd.WordNetLemmatizer()

words_lemmatized = {}

for i,word in enumerate(data_tokenized):
    word_afte = wnl.lemmatize(word)
    if(word_afte != word):
        words_lemmatized[i] = (word,word_afte)
end_time_task = time.time()
print("lemmatization time:",end_time_task-start_time_task)

#Synonyms-we will count the amout of words that have at least two synonyms
start_time_task = time.time()

from nltk.corpus import wordnet
words_with_synonyms = {}

for word in data_tokenized:
    synsets = wordnet.synsets(word)
    if len(synsets)>=2: #checks if there is at least two synonmys per word.
        synonyms = {lemma.name() for syn in synsets for lemma in syn.lemmas()}
        if len(synonyms) >= 2:  # Check if there are at least two distinct synonyms
            words_with_synonyms[word] = list(synonyms)

end_time_task = time.time()
print("Synonyms time:",end_time_task-start_time_task)

#stemming
start_time_task = time.time()
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")
word_stemed = {}

for i,word in enumerate(data_tokenized):
    stemed_word = stemmer.stem(word)
    if stemed_word != word:
        word_stemed[i] = (word,stemed_word)

end_time_task = time.time()
print("Stemming time:",end_time_task-start_time_task)
end_time = time.time()
exc_time = end_time-start_time_overall

# Display the results
print("The Results are in!")
print(f'The amount of lemmatized words: {len(words_lemmatized)}')
print(f'The amount of stemmed words: {len(word_stemed)}')
print(f'The amount of words with at least two synonyms: {len(words_with_synonyms)}')
print(f'The amount of NER entities found: {len(entites)}')
print(f'The amount of words with sense found (WSD): {len(word_senses)}')
print("Overall time it took:",exc_time)


Tokenization time: 1.7612321376800537
WSD time: 7260.057300329208
NER time: 84.98901629447937
lemmatization time: 1.7268247604370117
Synonyms time: 7.27872109413147
Stemming time: 4.529211521148682
The Results are in!
The amount of lemmatized words: 33513
The amount of stemmed words: 134885
The amount of words with at least two synonyms: 10405
The amount of NER entities found: 3
The amount of words with sense found (WSD): 257634
Overall time it took: 7360.344216585159


We found that The best organzation of the abiliites is the last test , and all the other tests preformed the same, but the last test was the fastest.

**lab 2 part 2**
In this part we will first examine 100 docs, and then for 1000 docs.
We will build in the end ,Matrix boolean and reversed indexes.

In [27]:
# #Lets start with taking 100 docs from our preprossced data.

import pickle
import numpy as np
import time
import string

# Load preprocessed data
with open('preprocessed_data.pkl', 'rb') as f:
    data = pickle.load(f)

# Create a dictionary of 100 documents
docs_100 = {f"doc_{i+1}": data[i] for i in range(min(100, len(data)))}



def preprocess_and_tokenize(doc):
    text = doc.get('text', '')  
    text = text.lower()  
    text = text.translate(str.maketrans("", "", string.punctuation))  
    return text.split()  


docs_100_tokenized = {doc: preprocess_and_tokenize(text) for doc, text in docs_100.items()}


query_words = ["space", "computers", "university"]  # Convert query words to lowercase

start_time_space = time.time()


bool_matrix = np.array([[int(word in doc) for word in query_words] for doc in docs_100_tokenized.values()])

# Count the total number of '1's (matches)
count = np.sum(bool_matrix)

# Print the results
print("Boolean Matrix of 100 :\n", bool_matrix)
print("Count of '1's:", count)

end_time_space = time.time()
print("It took:", end_time_space - start_time_space)

# Save the Boolean matrix to a Pickle file
with open("Bool_matrix_100_docs.pkl", "wb") as f:
    pickle.dump(bool_matrix, f)




Boolean Matrix of 100 :
 [[1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [1 0 1]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [1 0 1]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 1]
 [0 0 1]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [1 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [1 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]]
Count of '1's: 64
It took: 0.008994340896606445


In [28]:
#Lets work on 1000 documents and show the boolean matrix of it.
with open('preprocessed_data.pkl', 'rb') as f:
    data = pickle.load(f)

# Create a dictionary of 1000 documents
docs_100 = {f"doc_{i+1}": data[i] for i in range(min(1000, len(data)))}



def preprocess_and_tokenize(doc):
    text = doc.get('text', '')  
    text = text.lower()  
    text = text.translate(str.maketrans("", "", string.punctuation))  
    return text.split()  


docs_100_tokenized = {doc: preprocess_and_tokenize(text) for doc, text in docs_100.items()}


query_words = ["space", "computers", "university"]  # Convert query words to lowercase

start_time_space = time.time()


bool_matrix = np.array([[int(word in doc) for word in query_words] for doc in docs_100_tokenized.values()])

# Count the total number of '1's (matches)
count = np.sum(bool_matrix)

# Print the results
print("Boolean Matrix of 1000 :\n", bool_matrix)
print("Count of '1's:", count)

end_time_space = time.time()
print("It took:", end_time_space - start_time_space)

# Save the Boolean matrix to a Pickle file
with open("Bool_matrix_1000_docs.pkl", "wb") as f:
    pickle.dump(bool_matrix, f)


Boolean Matrix of 1000 :
 [[1 0 0]
 [1 0 0]
 [0 0 1]
 ...
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Count of '1's: 601
It took: 0.030632734298706055


**Now we will work on index reversing**

In [ ]:
#Lets start with 100 docs.
import pickle
import string
import time
import numpy as np

with open('preprocessed_data.pkl', 'rb') as f:
    data = pickle.load(f)

# Create a dictionary of 100 documents
docs_100 = {f"doc_{i+1}": data[i] for i in range(min(100, len(data)))}

def preprocess_and_tokenize(doc):
    text = doc.get('text', '')  
    text = text.lower()  
    text = text.translate(str.maketrans("", "", string.punctuation))  
    return text.split()  


docs_100_tokenized = {doc: preprocess_and_tokenize(text) for doc, text in docs_100.items()}


query_words = ["space", "computers", "university"]  

start_time_space = time.time()

inverted_index_query_words = {word: [] for word in query_words}

for doc_name, tokens in docs_100_tokenized.items():
    for word in query_words:
        word_count = tokens.count(word)  # Count occurrences of the query word
        if word_count > 0:
            inverted_index_query_words[word].append((doc_name, word_count))  

print("Inverted Index for Query Words:")
for word, doc_list in inverted_index_query_words.items():
    print(f"{word}: {doc_list}")


word_doc_counts = {}
for word, doc_list in inverted_index_query_words.items():
    doc_count = len(doc_list)  # Count the number of documents containing the word
    word_doc_counts[word] = doc_count  # Store the count for each word
    print(f"{word}: {doc_count} documents")
print("The amount it found",count)

end_time_space = time.time()
print("It took:", end_time_space - start_time_space)

with open("index_inverted_100_docs.pkl", "wb") as f:
    pickle.dump(inverted_index_query_words, f)


Inverted Index for Query Words:
space: [('doc_1', 1), ('doc_2', 1), ('doc_4', 1), ('doc_6', 1), ('doc_12', 3), ('doc_13', 1), ('doc_16', 71), ('doc_18', 1), ('doc_19', 1), ('doc_30', 3), ('doc_31', 3), ('doc_36', 3), ('doc_40', 5), ('doc_42', 4), ('doc_43', 1), ('doc_47', 1), ('doc_49', 2), ('doc_51', 2), ('doc_53', 3), ('doc_58', 1), ('doc_62', 4), ('doc_63', 1), ('doc_69', 2), ('doc_77', 1), ('doc_79', 3), ('doc_82', 4), ('doc_87', 1), ('doc_88', 5), ('doc_89', 1), ('doc_91', 1), ('doc_97', 4), ('doc_99', 1), ('doc_100', 4)]
computers: []
university: [('doc_3', 1), ('doc_8', 1), ('doc_13', 1), ('doc_17', 1), ('doc_19', 1), ('doc_21', 2), ('doc_22', 1), ('doc_26', 1), ('doc_31', 1), ('doc_32', 1), ('doc_34', 1), ('doc_36', 1), ('doc_41', 1), ('doc_44', 1), ('doc_45', 2), ('doc_51', 1), ('doc_57', 1), ('doc_59', 1), ('doc_62', 1), ('doc_63', 1), ('doc_66', 1), ('doc_77', 3), ('doc_78', 1), ('doc_79', 1), ('doc_82', 1), ('doc_83', 1), ('doc_90', 1), ('doc_94', 1), ('doc_95', 1), ('doc_9

In [16]:
#Now we will work on 1000 docs
with open('preprocessed_data.pkl', 'rb') as f:
    data = pickle.load(f)

# Create a dictionary of 1000 documents
docs_1000 = {f"doc_{i+1}": data[i] for i in range(min(1000, len(data)))}



def preprocess_and_tokenize(doc):
    text = doc.get('text', '')  
    text = text.lower()  
    text = text.translate(str.maketrans("", "", string.punctuation))  
    return text.split()  


docs_1000_tokenized = {doc: preprocess_and_tokenize(text) for doc, text in docs_1000.items()}


query_words = ["space", "computers", "university"]  

start_time_space = time.time()

inverted_index_query_words = {word: [] for word in query_words}

for doc_name, tokens in docs_1000_tokenized.items():
    for word in query_words:
        word_count = tokens.count(word)  # Count occurrences of the query word
        if word_count > 0:
            inverted_index_query_words[word].append((doc_name, word_count))  

print("Inverted Index for Query Words:")
for word, doc_list in inverted_index_query_words.items():
    print(f"{word}: {doc_list}")


word_doc_counts = {}
for word, doc_list in inverted_index_query_words.items():
    doc_count = len(doc_list)  # Count the number of documents containing the word
    word_doc_counts[word] = doc_count  # Store the count for each word
    print(f"{word}: {doc_count} documents")


end_time_space = time.time()
print("It took:", end_time_space - start_time_space)

with open("index_inverted_1000_docs.pkl", "wb") as f:
    pickle.dump(inverted_index_query_words, f)

Inverted Index for Query Words:
space: [('doc_1', 1), ('doc_2', 1), ('doc_4', 1), ('doc_6', 1), ('doc_12', 3), ('doc_13', 1), ('doc_16', 71), ('doc_18', 1), ('doc_19', 1), ('doc_30', 3), ('doc_31', 3), ('doc_36', 3), ('doc_40', 5), ('doc_42', 4), ('doc_43', 1), ('doc_47', 1), ('doc_49', 2), ('doc_51', 2), ('doc_53', 3), ('doc_58', 1), ('doc_62', 4), ('doc_63', 1), ('doc_69', 2), ('doc_77', 1), ('doc_79', 3), ('doc_82', 4), ('doc_87', 1), ('doc_88', 5), ('doc_89', 1), ('doc_91', 1), ('doc_97', 4), ('doc_99', 1), ('doc_100', 4), ('doc_101', 3), ('doc_105', 1), ('doc_108', 1), ('doc_113', 1), ('doc_114', 2), ('doc_116', 4), ('doc_118', 3), ('doc_124', 2), ('doc_128', 1), ('doc_129', 1), ('doc_131', 1), ('doc_134', 2), ('doc_137', 2), ('doc_139', 2), ('doc_142', 1), ('doc_147', 1), ('doc_150', 1), ('doc_152', 1), ('doc_158', 2), ('doc_160', 4), ('doc_163', 3), ('doc_171', 5), ('doc_183', 2), ('doc_190', 2), ('doc_194', 2), ('doc_195', 4), ('doc_197', 2), ('doc_203', 3), ('doc_206', 1), ('d

We see that the inverted index got the same results as boolean matrix but the inverted index found the answer faster,In this case the difference wasn't big but with larger sets of documents it might be a huge difference.

In [21]:
#Lets see the sizes of each file.
import os

# Filepath to your pickled file
file_path = "index_inverted_1000_docs.pkl"
file_path2 = "index_inverted_100_docs.pkl"
file_path3 = "Bool_matrix_1000_docs.pkl"
file_path4 = "Bool_matrix_100_docs.pkl"

# Get the size of the file in bytes
file_size = os.path.getsize(file_path)

print("Files of the inverted index\n")
print(f"Size of '{file_path}': {file_size / 1024:.2f} KB")  # Size in KB

print(f"Size of '{file_path2}': {file_size / 1024:.2f} KB\n")  # Size in KB
print("Files of the boolean matrix")

print(f"Size of '{file_path3}': {file_size / 1024:.2f} KB")  # Size in KB

print(f"Size of '{file_path4}': {file_size / 1024:.2f} KB")  # Size in KB

Files of the inverted index

Size of 'index_inverted_1000_docs.pkl': 7.51 KB
Size of 'index_inverted_100_docs.pkl': 7.51 KB

Files of the boolean matrix
Size of 'Bool_matrix_1000_docs.pkl': 7.51 KB
Size of 'Bool_matrix_100_docs.pkl': 7.51 KB
